### ISSUE TITLE
Multi-level extend does not work

### ISSUE THREAD

**Issue by kuwas** [probot/settings#110]
# Description

When using extend of a settings files that extends yet another settings file, the entirely functionality breaks.

### Repository A

* Probot settings works fine here

```
repository:
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
```

### Repository B

* Probot settings works fine here

```
_extends: repository-a
repository:
  allow_rebase_merge: false
```

### Repository C

* Probot settings stops working in this repository

```
_extends: repository-b
repository:
  description: "Repository C"
```
