### ISSUE TITLE
Branch protection not being applied

### ISSUE THREAD

**Issue by renatocaval** [probot/settings#150]
None of the repos where I have branch protection configured gets the settings applied. 

I did two different tests without success.

1. new repo without any rule, rules are not created
1. existing repo with rule for `master`, settings are not applied

Initially, I thought that this could be related to #136. That's why I did test num 2. 

Test were done on this repo: 
https://github.com/renatocaval/oh-my-git/
https://github.com/renatocaval/oh-my-git/blob/master/.github/settings.yml#L13-L23

**Comment by renatocaval** [comment]
You are right. It works if all top-level settings are included. 

Thanks for the tip. 

That's my current one:

```yaml
branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
      required_status_checks: null
      restrictions: null
      enforce_admins: null
```

I won't work if I set then to `false` like in:

```yaml
branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
      required_status_checks: false
      restrictions: false
      enforce_admins: false
```

**Comment by travi** [comment]
glad it got you unblocked. thanks for following up with the extra info. that'll be a big help when we get a chance to improve that situation. 

if you'd be interested in sending a PR to improve this, thats always appreciated and i'd be happy to help where you might need it.

**Comment by renatocaval** [comment]
We are now one huge release cycle involving many projects so I don't expect any bandwith before at least end November. Otherwise, I would be willing to help.

On the other hand, with a workaround, it makes it less urgent as well.

**Comment by travi** [comment]
not a problem. i'll leave the issue open until someone can clean that up and so others can hopefully find the workaround in the mean time.

**Comment by johnmartel** [comment]
Sorry for the noisy reference, I was trying to make this work, but was not actually able to, even after trying all possible combinations. I ended up with:

```yaml
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ['YAML lint']
      enforce_admins: null
      restrictions: null
```

The status check context I got from the API itself at `https://api.github.com/repos/john-badass-test-org/.github/branches/master/protection/required_status_checks`. The response is simple enough:
```json
{
    "url": "https://api.github.com/repos/john-badass-test-org/.github/branches/master/protection/required_status_checks",
    "strict": true,
    "contexts": [
        "YAML lint"
    ],
    "contexts_url": "https://api.github.com/repos/john-badass-test-org/.github/branches/master/protection/required_status_checks/contexts"
}
```

Any idea would be appreciated while I investigate a little further to see if I can get to the root of this.
