### ISSUE TITLE
modifying .github/settings.yml produces 29 DELETE for collaborators

### ISSUE THREAD

**Issue by sstarcher** [probot/settings#155]
The project already has all of its collaborators invited, but a single change to the settings produces 29 different instances of

```DEBUG github: GitHub request: DELETE /repos/:owner/:repo/collaborators/:username - 204 No Content (installation=xxx)```

The users are not collaborators of the org they are normal members of the org and the 29 don't seem to have any specific logic to why they have been chosen.  My overall concern is if we expand this to all of our repos we will easily run into API limits.  We currently have hundreds of repos.

**Comment by travi** [comment]
could you provide additional information? does the config file mention collaborators in some way? could you list the collaborators in the file if you aren't already? do you have a public example config file that you could link to that has this behavior?

**Comment by sstarcher** [comment]
Yes, the config file calls out a single collaborator.  The repo currently has 5 collaborators but attempts to delete 29.  I can attempt to create it on a public repo, but it may be difficult.

**Comment by sstarcher** [comment]
Here is the configuration I'm using, but I'm running my own probot.

```
  
repository:
  description: Please specify the repo name in .github/settings.yml
  private: true
  has_issues: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  
teams:
  - name: engineering
    permission: push  
    
collaborators: []    

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        users: []
        teams:
        - engineering
```
