### ISSUE TITLE
Branch protection with specified team exceptions

### ISSUE THREAD

**Issue by ryanbrookepayne** [probot/settings#205]
## Scenario

I have a repository that only contains documentation—markdown files and images. The core team who manages the repo (codeowners) makes updates to the documentation frequently.

## Goal

We've decided that we don't want to require pull request approval to make changes to doc files. But, we still want to require pull request approval for all outside (non-codeowner) contributors.

## Attempted Solution

I attempted to accomplish my desired outcome with the the following configuration.

```yml
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        require_code_owner_reviews: false
      restrictions:
        teams:
          - example-team-name
```

However, the configuration did not accomplish my goal.

How do I enable branch protection while allowing specific individuals or teams to change files without review?

**Comment by ryanbrookepayne** [comment]
I solved this issue by setting the `users` setting to an empty list.

```yml
branches:
  - name: master
    protection:
      required_pull_request_reviews:
      restrictions:
        teams:
          - example-team-name
        users: []
```
