### ISSUE TITLE
Milestones Are not working

### ISSUE THREAD

**Issue by maheshrajannan** [probot/settings#225]
## Problem Description

Changing the milestones below in ./github/settings.yml has no effect on either existing milestones or new milestones and there are no new milestones created.

```
# Milestones: define milestones for Issues and Pull Requests
milestones:
  - title: bot-milestone-title
    description: bot-milestone-description
    # The state of the milestone. Either `open` or `closed`
    state: open
```

### What is actually happening

Changing the milestones below in ./github/settings.yml has no effect on either existing milestones or new milestones and there are no new milestones created.

### What is the expected behavior

It should have some effect to start with.

### Error output, if available

```

```

### Are you using the hosted instance of probot/settings or running your own?
Yes.
### If running your own instance, are you using it with github.com or GitHub Enterprise?
Github Enterprise
#### Version of probot/settings
latest.
#### Version of GitHub Enterprise
GitHub Enterprise Server 2.20.0
