### ISSUE TITLE
maintain permissions do not apply on teams

### ISSUE THREAD

**Issue by mkrakowitzer** [probot/settings#246]
## Problem Description

maintain permissions do not apply on teams as documented. The API seems to support this behaviour https://developer.github.com/v3/repos/collaborators/

```
teams:
  - name: team1
    permission: maintain
  - name: team2
    permission: maintain
```

The above works on pull, push and admin no problem. If I switch it to maintain it does not apply the change.

### What is actually happening
I assume it's hitting an error because when `maintain` permissions are set as no changes apply to anything in the settings module.

### What is the expected behaviour
Teams should get the maintain permissions

### Error output, if available

```

```

### Are you using the hosted instance of probot/settings or running your own?
Using the hosted version

#### Version of GitHub Enterprise
Enterprise Cloud
