### ISSUE TITLE
Cannot add team permissions and team restrictions in same commit

### ISSUE THREAD

**Issue by jrmash** [probot/settings#249]
## Problem Description
Adding team permissions and team restrictions (in branch protections) in the same commit does not appear to work:

```
teams:
  - name: Admins
    permission: admin
branches:
  - name: master
    protection:
      restrictions:
        teams: 
          - admins
```

### What is actually happening
Permissions are added for the team as expected, but the restrictions are not.  This can be circumvented by performing two commits (either splitting the commit in two pieces, or making the whole change in the first and pushing a second whitespace-only type change).

We ran into this when creating a new repository from our one of our repo templates that has the `settings.yml` already committed, which makes the two-step commit a bit more difficult to deal with.

### What is the expected behavior
Permissions for the team would be added, then the restrictions would be added.

### Are you using the hosted instance of probot/settings or running your own?
I am using the hosted instance of `probot/settings`.
