### ISSUE TITLE
Only some labels are actually applied to the repository

### ISSUE THREAD

**Issue by gdude2002** [probot/settings#259]
## Problem Description

For whatever reason, given a set of labels in the `settings.yml`, they don't all seem to be created together within a repository.

### What is actually happening

We have [14 labels defined](https://github.com/Kotlin-Discord/.github/blob/master/.github/settings.yml#L15). However, only 11 of them are created the first time around. It seems that the labels that aren't created are the first three - `Duplicate`, `Good First Issue` and `Invalid`.

If the `settings.yml` ([referred to like this](https://github.com/Kotlin-Discord/kord-extensions/blob/master/.github/settings.yml), for example) is updated, then the rest of the labels are created.

Please note that I've manually created the missing labels in these repositories.

### What is the expected behaviour

All labels should be created together when the `settings.yml` is put in place.

### Are you using the hosted instance of probot/settings or running your own?

I'm using the hosted instance.

**Comment by stocky37** [comment]
FWIW, I'm seeing the same thing.

**Comment by travi** [comment]
finding time to investigate some of these details has been difficult for me lately. if someone is able to dig deep enough to understand why this is happening, it would be a big help for moving this forward. if i were to take a guess, it likely is related to pagination. a PR would be a huge help, if someone is willing to go that far.

**Comment by stocky37** [comment]
I might be able to make some time over the weekend to do what I can.

**Comment by stocky37** [comment]
It looks like I had two separate issues:
- If the label description is longer than the limit it will be skipped
- Color field not surrounded by quotes, with aleading digit (with alpha chars - e.g. `color: 5aaaaa`) would fail in different ways - sometimes not applying, sometimes applying with no color

**Comment by Josee9988** [comment]
Same here :(

**Comment by SVendittelli** [comment]
I am getting this issue too

**Comment by mdelapenya** [comment]
Still seeing this. Playing with the default settings.yml file:

Pushing this file:
```yaml
labels:
  - name: "type/bug"
    color: '#CC0000'
    description: An issue with the system 🐛.

  - name: "type/feature"
    # If including a `#`, make sure to wrap it with quotes!
    color: '#336699'
    description: New functionality.

  - name: "Help Wanted"
    # Provide a new name to rename an existing label
    new_name: first-timers-only
```

Generates **only** two labels: `Help Wanted` and `type/feature`. `type/bug` is never created

I pushed changes to the yaml file (label names without quoted):
```yaml
labels:
  - name: type/bug
    color: '#CC0000'
    description: An issue with the system 🐛.

  - name: type/feature
    # If including a `#`, make sure to wrap it with quotes!
    color: '#336699'
    description: New functionality.

  - name: Help Wanted
    # Provide a new name to rename an existing label
    new_name: first-timers-only
```

And it generated two different labels for the help wanted:

<img width="1252" alt="Screenshot 2022-09-15 at 09 59 29" src="https://user-images.githubusercontent.com/951580/190348793-9f902657-576a-4f51-ac60-6041b947143c.png">

The one for bugs never appeared.

I can observe that with every push, the label with `new_name` is alternatively passing from `first-times-only` to `Help wanted` and viceversa.

**Comment by MAN-Sendance** [comment]
It is still a significant issue

**Comment by MAN-Sendance** [comment]
> It is still a significant issue.
> 
> It seems that the bot cannot add more than 40 labels.

In fact, it was my fault. I didn't recognize that description is limited to 100 characters which are why only the labels with a valid length of description have been added.

**Comment by TaffarelJr** [comment]
I'm experiencing this as well. I have 23 labels being created, with this one being left out consistently:

```yml
  - name: Dev Containers
    color: 2753e3
    description: Updates to Dev Container Features
```

None of my other color values use quotes; YAML just picks them all up as strings and they work fine.
But for some reason, this particular one does not.
The resolution was to add quotes and `#`:

```yml
  - name: Dev Containers
    color: '#2753e3'
    description: Updates to Dev Container Features
```
