### ISSUE TITLE
Branch protection settings not applied

### ISSUE THREAD

**Issue by alvarosanchez** [probot/settings#267]
## Problem Description

Branch protection rules are not created

### Are you using the hosted instance of probot/settings or running your own?

Hosted

----

Is there something wrong in this YAML?

```yaml
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions: {}

      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts:
          - build (8)
          - build (11)
          - build (14)
          - license/cla
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: null

      # Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to true to enforce a linear commit history. Set to false to disable a linear commit Git history. Your repository must allow squash merging or rebase merging before you can enable a linear commit history. Default: false. For more information, see "Requiring a linear commit history" in the GitHub Help documentation.
      required_linear_history: true

      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users:
          - micronaut-build
```

The `repository.allow_*` settings were applied correctly, but the branch protection ones were not.

**Comment by travi** [comment]
branch protection is certainly one of the most finicky sections to configure, as it does fail if just about anything is out of place.

i did happen to configure one of these successfully just last night, so i do know that it is working in a general sense. this is that config in case comparing against a working one makes anything stand out:https://github.com/dsmjs/twitter-together/blob/8cf4774b75ade4ea0da99c2bcf69bf181aa59d08/.github/settings.yml#L9-L22

typically, the thing that gets folks is making sure that the required properties are set to `null` rather than being left off when it is not something they wish to configure, but it looks like you took steps to handle at least most of those. the one that does make me wonder is the restrictions. i haven't personally enabled that myself, so i don't know the exact requirements, but i wonder if `teams` is required, even as an empty list.

one other thing that can sometimes help is to curl for the current details to see how the github api represents them. if you make adjustments through the ui and then see how they are represented in the api, it can point out some things that might not be obvious. i know this defeats the purpose of doing this through settings, but especially if you are trying to apply similar config to several repos, it can help you find the proper shape to apply across all of them.

**Comment by alvarosanchez** [comment]
Whoa, you were right! Adding empty `apps` and `teams` arrays made it work! For future reference, this is the final configuration that works:

```yaml
repository:
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}

      required_status_checks:
        strict: true
        contexts:
          - build (8)
          - build (11)
          - build (14)
          - license/cla
      enforce_admins: null

      required_linear_history: true

      restrictions:
        users:
          - micronaut-build
        apps: []
        teams: []
```
