### ISSUE TITLE
Repository visibility settings

### ISSUE THREAD

**Issue by jurijzahn8019** [probot/settings#359]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
<https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-repository-visibility#about-internal-repositories>

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
<https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-a-repository>

## New Feature

Add setting to set repository visiblity to "internal" (or other allowed value)

e.g. 

```yaml
repository:
  # allowed values: private, public or internal (enterprise only)
  visibility: "internal"
```
