### ISSUE TITLE
_extends not working for me

### ISSUE THREAD

**Issue by ScottChapman** [probot/settings#404]
I'm working in my own personal org (also using GHE so deployed my own own instance of the bot). It works great with settings for a repo, but I'm not getting `_extends` to work. My inheritance looks like:

MyTestSetupRepo:
.github/settings.yml (contains good stuff that works for this repo)

mytestrepo:
.github/settings.yml:
```yml
_extends: MyTestSetupRepo
  repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository

  name: mytestrepo

  # A short description of the repository that will show up on GitHub
  description: new description of repo

  # A URL with more information about the repository
  homepage: https://example.github.io/

  # A comma-separated list of topics to set on the repository
  topics: newone
```

The topic `newone` does get created, but nothing from `MyTestSetupRepo` gets created.
