### ISSUE TITLE
Labels do not update

### ISSUE THREAD

**Issue by core23** [probot/settings#407]
## Problem Description

I've added some new labels and renamed a few, but only the new labels are created and the old did not change. 

```yaml
# settings.yml
labels:
  - name: "BC Break"
    color: "#ff0000"
    description: ""
    oldname: "bc break"

  - name: "Bug"
    color: "#fc2929"
    description: ""
    oldname: "bugfix"

  - name: "Enhancement"
    color: "#5fb2d8"
    description: ""
```

### What is actually happening

Existing labels do not change (e.g. rename "bug" to "Bug")

### What is the expected behavior

Label is renamed.

### Are you using the hosted instance of probot/settings or running your own?

Using probot app on github.com 

---

Is there any option to get logs / debug information for the app?
