### ISSUE TITLE
Adding user or team to restrictions doesn't allow them to merge to protected branch

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [probot/settings#451]
## Problem Description

Having added a user to the restrictions section of branch protect, a user should be able to push to the protected branch. 

This is the branches section of our settings.yml file.

```
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        apps: []
        users: [username]
        teams: []
```

### What is actually happening

This doesn't work. The users are added to the list, but their push to the branch is denied or forced to open a new branch. We have tried this via git on the user's local env and via the GitHub UI. 

### What is the expected behavior
The user in the restricted user list should be able to push to the expected branch.

### Error output, if available

```

```

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of probot/settings
Latest, it's installed as a GitHub app, so I assume it updates automagically.
