### ISSUE TITLE
Require Conversation Resolution Before Merging Protection Rule

### ISSUE THREAD

**Issue by SamuelCabralCruz** [probot/settings#458]
## Prerequisites:

![image](https://user-images.githubusercontent.com/15621634/121784544-6d028200-cb82-11eb-9b2d-49e69eee689b.png)

* [GitHub Docs](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-conversation-resolution-before-merging)
* I couldn't find API availability - however I'm not that familiar with GitHub API docs so it might be.

## New Feature
Request: A config field allowing the repository settings "Require conversation resolution before merging" to be controlled.

**Comment by foolioo** [comment]
just add the following

```yaml
branches:
  - name: master
    protection:
      required_conversation_resolution: true
```
