### ISSUE TITLE
Branch protection settings not working for Apps & Teams

### ISSUE THREAD

**Issue by pamelasarkisyan** [probot/settings#474]
## Problem Description:
Branch protection created but settings doesn't add both teams and apps to "Restrict who can push to matching branches" section

### What is actually happening
1) 
```
      restrictions:
        teams: 
          - TeamName
        apps: []
        users: []
```
The above adds TeamName as expected to restriction section in branch protection settings.

2) 
```
      restrictions:
        teams: 
          - TeamName
        apps: 
          - bulldozer
        users: []
```
The above adds only `bulldozer` app but TeamName is **not** added to restriction section in branch protection settings.

### What is the expected behavior
When teams and apps are set, both should be added to restrictions section.
