### ISSUE TITLE
Support for Autolink References

### ISSUE THREAD

**Issue by tomislacker** [probot/settings#481]
## Prerequisites:

* **Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.**

    Yes. It's available at the `github.com/<user/group>/<projectname>/settings/key_links` URL

* **Is the functionality available through the GitHub API? If the functionality is available, please provide links to the API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).**
  
    Yes. API support was [finally] unveiled on 2021-08-02 with [this announcement](https://github.blog/changelog/2021-08-02-apis-for-autolinks/)

## New Feature

I'm not filing this ticket with any defined schema in-mind that I feel strongly about, but I would at least propose some sort of functionaly like:

```yaml
references:
  'ASDF-': 'https://jira.company.com/browse/ASDF-<num>'
  'BOLIGRAFO-': 'https://jira.company.com/browse/BOLIGRAFO-<num>'
```

Where the probot/settings application would be able to manage the _Autolink References_ in a project.
