### ISSUE TITLE
Support to delete/remove labels

### ISSUE THREAD

**Issue by patcon** [probot/settings#80]
Hi again!

I'm seeing the ability to delete/remove labels in [`settings/lib/plugins/labels.js`](https://github.com/probot/settings/blob/38883637e0786c6fc3320de36a155b3598d6d69e/lib/plugins/labels.js), but am I correct in finding that it hasn't been implemented yet?

It seems fairly niche, but for creating starter project templates for tech and GitHub beginners, it would be nice to clean-up the default GitHub labels to make things as clear as possible, in case they don't suit a project type :)

Any preference on how this might be done? My first inclination ~is to allow this~ would be to allow one of these:

```yml
# option A
labels:
  - name: wontfix
    delete: true

# option B
labels:
  - deletename: wontfix

# option C
labels:
  - oldname: wontfix
```

Before I jump in, can anyone offer advice on:
- What's possible with current arch?
- Are any of the above are good or bad patterns?

Thanks!
